/* Spanish language pack. Keys are the English source strings (see tools/strings.json).
 * Parody names of managers are intentionally left in English. */
I18N.register('es', {
  "Not available during the weekend event": "No disponible durante el evento de fin de semana",
  "Your treasury is overflowing!": "¡Tu tesoro se desborda!",
  "Your Cabinet has been earning all night. Come collect!": "Tu Gabinete ha estado ganando toda la noche. ¡Ven a cobrar!",
  "{n} achievements unlocked": "{n} logros desbloqueados",
  "×10 profit on every main world for 15 minutes.": "Ganancias ×10 en todos los mundos principales durante 15 minutos.",
  "Permanent ×2 profit on every main world (not the weekend event). Stacks! Price doubles each purchase.": "Ganancias ×2 permanentes en todos los mundos principales (no en el evento de fin de semana). ¡Se acumula! El precio se duplica con cada compra.",
  "Permanent ×3 profit on every main world, no ads ever (all ad rewards are free), and 250 ★.": "Ganancias ×3 permanentes en todos los mundos principales, nunca más anuncios (todas las recompensas de anuncios son gratis) y 250 ★.",
  "(Simulated ad in the web build)": "(Anuncio simulado en la versión web)",
  "(Store unavailable in this build — purchases are simulated.)": "(Tienda no disponible en esta versión: las compras se simulan).",
  "(capped at {d} — connect to the internet to verify longer absences)": "(límite de {d}: conéctate a internet para verificar ausencias más largas)",
  "+30 seconds of ×5 speed.": "+30 segundos de velocidad ×5.",
  "+{n} Amendments — all profit ×{m}": "+{n} Enmiendas: todas las ganancias ×{m}",
  "+{n} Liberty Bucks": "+{n} Libertólares",
  "+{n} free <b>{biz}</b>": "+{n} <b>{biz}</b> gratis",
  "+{n} from the sky.": "+{n} caídos del cielo.",
  "+{n} more achievements": "+{n} logros más",
  "/sec": "/s",
  "10 minutes": "10 minutos",
  "1h warp": "Salto de 1 h",
  "<b>{a} / {b}</b> unlocked. Each achievement pays out <b>★ Liberty Bucks</b>.": "<b>{a} / {b}</b> desbloqueados. Cada logro paga <b>★ Libertólares</b>.",
  "<b>{biz}</b> profit ×{n}": "Ganancias de <b>{biz}</b> ×{n}",
  "<b>{p}</b> effectiveness +{n}%": "Efectividad de <b>{p}</b> +{n}%",
  "A Constitutional Convention will <b>reset all four worlds</b> — cash, businesses, upgrades, managers and prestige currency. In return you ratify <b>+{n} Amendments</b>: ×{m} profit everywhere, forever. Liberty Bucks, badges, achievements and purchases are kept.": "Una Convención Constitucional <b>reinicia los cuatro mundos</b>: dinero, negocios, mejoras, gerentes y moneda de prestigio. A cambio ratificas <b>+{n} Enmiendas</b>: ganancias ×{m} en todas partes, para siempre. Conservas Libertólares, insignias, logros y compras.",
  "A bill is ready to pass! Visit <b>⬆️ Upgrades</b> to triple a business's profits.": "¡Hay un proyecto de ley listo! Visita <b>⬆️ Mejoras</b> para triplicar las ganancias de un negocio.",
  "A chicken in every pot, and a rocket in every garage!": "¡Un pollo en cada olla y un cohete en cada garaje!",
  "A citizen brought a petition!": "¡Un ciudadano trajo una petición!",
  "A weekend of fireworks, floats and freedom": "Un fin de semana de fuegos artificiales, carrozas y libertad",
  "About": "Acerca de",
  "Accessibility": "Accesibilidad",
  "Achievements": "Logros",
  "Achievements, missions, daily rewards, weekend events and the flying bonus.": "Logros, misiones, recompensas diarias, eventos de fin de semana y el bonus volador.",
  "Ad privacy choices": "Privacidad de anuncios",
  "Admin console found running on a very old operating system": "Descubren que la consola de administración usa un sistema operativo antiquísimo",
  "Alien Allies": "Aliados Alienígenas",
  "Alien Embassy Booth": "Caseta de Embajada Alien",
  "Alien Treaties": "Tratados Alienígenas",
  "Alien Treaty": "Tratado Alienígena",
  "Aliens confused by electoral college; so are we": "Los alienígenas no entienden el colegio electoral; nosotros tampoco",
  "All complete!": "¡Todo completado!",
  "All milestones reached!": "¡Todos los hitos alcanzados!",
  "All profit now ×{n} forever.": "Todas las ganancias ahora ×{n} para siempre.",
  "All worlds, Liberty Bucks and achievements on this device and in iCloud will be erased. Purchases can be restored.": "Se borrarán todos los mundos, Libertólares y logros de este dispositivo y de iCloud. Las compras se pueden restaurar.",
  "All-inclusive. Rings extra.": "Todo incluido. Anillos aparte.",
  "Allies": "Aliados",
  "Ambassador of Hellos": "Embajador de los Saludos",
  "Amendments": "Enmiendas",
  "Amendments ratified!": "¡Enmiendas ratificadas!",
  "Amendments: {n}": "Enmiendas: {n}",
  "An alien envoy has arrived!": "¡Ha llegado un enviado alienígena!",
  "An envoy is waiting!": "¡Un enviado está esperando!",
  "Anchor-in-Chief": "Presentador en Jefe",
  "Annex the Universe": "Anexar el Universo",
  "Apple Pie Diner": "Cafetería de Tarta de Manzana",
  "Apple pie futures hit all-time high": "Los futuros de tarta de manzana alcanzan máximos históricos",
  "Appoint a manager to run a business automatically — forever, even offline. Managers can then be promoted to Cabinet Secretary, making that business 90% cheaper to expand.": "Nombra un gerente para que dirija un negocio automáticamente, para siempre, incluso sin conexión. Después puedes ascenderlo a Secretario de Gabinete, y ampliar ese negocio costará un 90% menos.",
  "Appoint every Cabinet Secretary on {world}.": "Nombra a todos los Secretarios de Gabinete en {world}.",
  "As American as… well.": "Tan americana como… bueno.",
  "Ask not what your galaxy can do for you…": "No preguntes qué puede hacer tu galaxia por ti…",
  "Asteroid Boss": "Jefe de Asteroides",
  "Asteroid Mining Rig": "Plataforma Minera de Asteroides",
  "Asteroid belt rebranded \"Asteroid Suspenders\" for extra hold": "El cinturón de asteroides pasa a llamarse \"tirantes de asteroides\" para sujetar mejor",
  "At <b>{at}</b>: {what}": "A las <b>{at}</b>: {what}",
  "Auto": "Auto",
  "Available": "Disponibles",
  "Awaiting the next envoy…": "Esperando al próximo enviado…",
  "Backyard BBQ Grill": "Parrilla de Patio",
  "Bag of Liberty": "Bolsa de Libertad",
  "Bald Eagle Hatchery": "Criadero de Águilas Calvas",
  "Bald eagle population surpasses human population in Ohio": "La población de águilas calvas supera a la humana en Ohio",
  "Balloon Handler": "Encargado de Globos",
  "Band Leader": "Director de Banda",
  "Best value": "Mejor valor",
  "Big Bang Reenactment": "Recreación del Big Bang",
  "Big Bang reenactment sells out every seat in every dimension": "La recreación del Big Bang agota entradas en todas las dimensiones",
  "Bipartisan": "Bipartidista",
  "Black Hole Casino": "Casino Agujero Negro",
  "Black hole casino reports record losses — for everyone but the house": "El casino agujero negro reporta pérdidas récord… para todos menos la casa",
  "Bounce Supervisor": "Supervisor de Rebotes",
  "Breaking news, around the clock.": "Noticias de última hora, a todas horas.",
  "Brighter than a trillion suns.": "Más brillante que un billón de soles.",
  "Brrrrrrrr.": "Brrrrrrrr.",
  "Build the Warp Gate": "Construir la Puerta Warp",
  "Burgers, dogs, and patriotism.": "Hamburguesas, perritos y patriotismo.",
  "Businesses tapped": "Negocios tocados",
  "Buy": "Comprar",
  "Buy 25 of a business to double its speed. Milestones stack!": "Compra 25 de un negocio para duplicar su velocidad. ¡Los hitos se acumulan!",
  "Buy all affordable ({n})": "Comprar todo lo posible ({n})",
  "Buy quantity": "Cantidad a comprar",
  "Buy {n} {biz} for {cost}. You own {owned}.": "Comprar {n} {biz} por {cost}. Tienes {owned}.",
  "Buy ×{n}": "Comprar ×{n}",
  "Cabinet": "Gabinete",
  "Cabinet Secretaries make a business 90% cheaper to expand.": "Los Secretarios de Gabinete abaratan un 90% la ampliación de un negocio.",
  "Cabinet Secretary": "Secretario de Gabinete",
  "Cabinet Secretary appointed": "Secretario de Gabinete nombrado",
  "Cable News Network": "Canal de Noticias 24 h",
  "Cable news anchor reports on self reporting on self": "Presentador informa sobre sí mismo informando sobre sí mismo",
  "Campaign Finance Reform {r}": "Reforma de Financiación de Campañas {r}",
  "Campaign Promises": "Promesas de Campaña",
  "Cancel": "Cancelar",
  "Catch the flying bonus for cash or Liberty Bucks!": "¡Atrapa el bonus volador para ganar dinero o Libertólares!",
  "Catch {n} flying bonuses.": "Atrapa {n} bonus voladores.",
  "Cha-ching! Buy another Flag Stand to earn more per tap.": "¡Cha-ching! Compra otro Puesto de Banderas para ganar más por toque.",
  "Cheese Foreman": "Capataz del Queso",
  "Chief Actuary": "Actuario Jefe",
  "Chief Eagle Wrangler": "Domador Jefe de Águilas",
  "Citizens are drafting petitions…": "Los ciudadanos redactan peticiones…",
  "Citizens drop by with petitions. Sign one for an instant cash bonus.": "Los ciudadanos traen peticiones. Firma una para ganar un bonus de dinero al instante.",
  "Claim": "Reclamar",
  "Claim ({n})": "Reclamar ({n})",
  "Claim Day {n}": "Reclamar día {n}",
  "Claimed": "Reclamado",
  "Clock changed": "El reloj cambió",
  "Clone Senate": "Senado de Clones",
  "Clone Senate passes bill 100–0, again, forever": "El Senado de Clones aprueba la ley 100–0, otra vez, para siempre",
  "Close": "Cerrar",
  "Collect": "Cobrar",
  "Collected {x}.": "Cobrado: {x}.",
  "Colonial Tribute!": "¡Tributo Colonial!",
  "Color-blind friendly": "Modo daltónico",
  "Come back tomorrow!": "¡Vuelve mañana!",
  "Commander of Flags": "Comandante de Banderas",
  "Complete Missions for Liberty Bucks. Three are active at a time.": "Completa Misiones para ganar Libertólares. Hay tres activas a la vez.",
  "Complete missions to earn ★ Liberty Bucks. Three are active at a time.": "Completa misiones para ganar ★ Libertólares. Hay tres activas a la vez.",
  "Complete {n} missions.": "Completa {n} misiones.",
  "Congress agrees on something; historians baffled": "El Congreso se pone de acuerdo en algo; los historiadores, perplejos",
  "Constitution amended to include \"and also everything else\"": "Se enmienda la Constitución para incluir \"y también todo lo demás\"",
  "Constitutional": "Constitucional",
  "Constitutional Convention": "Convención Constitucional",
  "Convene": "Convocar",
  "Convene (+{n})": "Convocar (+{n})",
  "Copied to clipboard.": "Copiado al portapapeles.",
  "Cosmic Delegates": "Delegados Cósmicos",
  "Cosmic String Yo-Yo Co.": "Yoyós de Cuerda Cósmica S.A.",
  "Cul-de-sacs the size of galaxies.": "Callejones sin salida del tamaño de galaxias.",
  "Current streak: {n} days": "Racha actual: {n} días",
  "Daily Reward": "Recompensa diaria",
  "Dark Matter Czar": "Zar de la Materia Oscura",
  "Dark Matter Refinery": "Refinería de Materia Oscura",
  "Day {n}": "Día {n}",
  "Day {n} reward!": "¡Recompensa del día {n}!",
  "Decorated Patriot {n}": "Patriota Condecorado {n}",
  "Deep State ({world})": "Estado Profundo ({world})",
  "Delegates": "Delegados",
  "Deluxe": "de Lujo",
  "Destination: everywhere.": "Destino: todas partes.",
  "Destination: {world}": "Destino: {world}",
  "Director of Liftoff": "Director de Despegue",
  "Doctrine Realtor": "Agente Inmobiliario Doctrinal",
  "Dollars": "Dólares",
  "Donors": "Donantes",
  "Double it!": "¡Duplícalo!",
  "Doubled!": "¡Duplicado!",
  "Drill, baby, drill.": "Perfora, nena, perfora.",
  "Dyson Sphere Co.": "Esfera de Dyson S.A.",
  "Dyson Sphere construction delayed by permit dispute with the Sun": "Obras de la Esfera de Dyson retrasadas por un litigio de permisos con el Sol",
  "E Pluribus Profit!": "¡E Pluribus Ganancias!",
  "E Pluribus {n}": "E Pluribus {n}",
  "Each Liberty Badge permanently boosts profit on every world by +{n}%. Badges and ★ are yours to keep after the event ends.": "Cada Insignia de la Libertad aumenta para siempre las ganancias de todos los mundos un +{n}%. Las insignias y ★ son tuyas aunque termine el evento.",
  "Eagle Standard": "Patrón Águila",
  "Earn more to attract supporters": "Gana más para atraer simpatizantes",
  "Earn {amount} all-time": "Gana {amount} en total",
  "Earn {amount} all-time.": "Gana {amount} en total.",
  "Earn {n} Liberty Badges.": "Consigue {n} Insignias de la Libertad.",
  "Earth": "Tierra",
  "Election Day": "Día de Elecciones",
  "Election Night Extravaganza": "Gran Noche Electoral",
  "Enable them for Star-Spangled Tycoon in iOS Settings.": "Actívalas para Star-Spangled Tycoon en Ajustes de iOS.",
  "Ends in": "Termina en",
  "Entropy Insurance": "Seguros contra la Entropía",
  "Entropy Insurance denies claim citing \"act of physics\"": "Seguros contra la Entropía rechaza un reclamo alegando \"causa física mayor\"",
  "Envoys arrive with trade deals. Pick one of two treaties — each reshapes your economy for 10 minutes.": "Llegan enviados con acuerdos comerciales. Elige uno de dos tratados: cada uno transforma tu economía durante 10 minutos.",
  "Erase my empire": "Borrar mi imperio",
  "Eternal": "Eterno",
  "Eternal Surplus": "Superávit Eterno",
  "Event rewards claimed!": "¡Recompensas del evento reclamadas!",
  "Every 25 of a business doubles its speed! Grow your empire until you have $1,000.": "¡Cada 25 unidades de un negocio duplican su velocidad! Haz crecer tu imperio hasta tener $1,000.",
  "Every Friday–Sunday. Next one starts in {t}.": "Cada viernes a domingo. El próximo empieza en {t}.",
  "Every business": "Todos los negocios",
  "Every business at {n}: all profit ×{m}": "Todos los negocios en {n}: ganancias ×{m}",
  "Every day is the Fourth.": "Todos los días son 4 de julio.",
  "Every mission complete. Legendary!": "Todas las misiones completadas. ¡Legendario!",
  "Every promise kept!": "¡Todas las promesas cumplidas!",
  "Every world earns in the background. Launching a new world gives the previous one a permanent ×5 Colonial Tribute!": "Todos los mundos generan en segundo plano. ¡Lanzar un mundo nuevo da al anterior un Tributo Colonial permanente de ×5!",
  "Every world runs its own economy — and they all keep earning while you're away. Launching a new world grants the previous one a permanent ×{n} Colonial Tribute.": "Cada mundo tiene su propia economía, y todos siguen ganando mientras no estás. Lanzar un mundo nuevo otorga al anterior un Tributo Colonial permanente de ×{n}.",
  "Everything was already up to date.": "Todo estaba al día.",
  "Exact change only.": "Solo cambio exacto.",
  "Executive": "Ejecutivo",
  "Exoplanet Real Estate": "Inmobiliaria de Exoplanetas",
  "Export": "Exportar",
  "Father of Everything": "Padre de Todo",
  "Fed prints commemorative trillion-dollar bill, spends it on snacks": "La Fed imprime un billete conmemorativo de un billón y se lo gasta en aperitivos",
  "Federal": "Federal",
  "Federal Grant: {biz}": "Subsidio Federal: {biz}",
  "Federal Reserve Printer": "Imprenta de la Reserva Federal",
  "Fest Bucks": "Festidólares",
  "Fest earnings": "Ganancias del festival",
  "Finish tutorial": "Terminar tutorial",
  "Fireworks Factory": "Fábrica de Fuegos Artificiales",
  "Fireworks now legally classified as a food group": "Los fuegos artificiales ya son legalmente un grupo alimenticio",
  "First Term ({world})": "Primer Mandato ({world})",
  "Flag Stand": "Puesto de Banderas",
  "Flare extended!": "¡Llamarada extendida!",
  "Float Seamstress": "Costurera de Carrozas",
  "Flyover Captain": "Capitán de Sobrevuelo",
  "Food court in every orbit.": "Patio de comidas en cada órbita.",
  "Forge Master": "Maestro de la Forja",
  "Fort Knox": "Fort Knox",
  "Founding Father {n}": "Padre Fundador {n}",
  "Founding Fathers Pack": "Pack Padres Fundadores",
  "Founding Fathers Pack unlocked: ×3 profit and no ads, forever.": "Pack Padres Fundadores desbloqueado: ganancias ×3 y sin anuncios, para siempre.",
  "Founding Fathers get it free — {n} left today": "Gratis para Padres Fundadores: quedan {n} hoy",
  "Four more years! Four more years!": "¡Cuatro años más! ¡Cuatro años más!",
  "Four score and seven light-years ago…": "Hace ochenta y siete años luz…",
  "Free Liberty Bucks": "Libertólares gratis",
  "Freedom Act": "Ley de la Libertad",
  "Freedom Fest": "Festival de la Libertad",
  "Freedom Fest is here! Build the biggest party in the galaxy before Monday. Every reward tier earns Liberty Bucks and a permanent Liberty Badge.": "¡Llegó el Festival de la Libertad! Monta la mayor fiesta de la galaxia antes del lunes. Cada nivel de recompensa da Libertólares y una Insignia de la Libertad permanente.",
  "Freedom Fest runs every weekend. Its reward tiers grant permanent Liberty Badges.": "El Festival de la Libertad se celebra cada fin de semana. Sus niveles de recompensa otorgan Insignias de la Libertad permanentes.",
  "Freedom Multiplier": "Multiplicador de Libertad",
  "Freedom Store": "Tienda de la Libertad",
  "Freedom ore. Very shiny.": "Mineral de libertad. Muy brillante.",
  "Freedom-Grade": "Grado Libertad",
  "From sea to shining star": "De mar a estrella brillante",
  "Full Cabinet ({world})": "Gabinete Completo ({world})",
  "Fund the Moonshot": "Financiar el viaje a la Luna",
  "Gain on election": "Ganancia en elecciones",
  "Galactic Congress filibuster enters third millennium": "El obstruccionismo del Congreso Galáctico entra en su tercer milenio",
  "Galactic Credits": "Créditos Galácticos",
  "Galactic Freedom Initiative": "Iniciativa Galáctica de Libertad",
  "Galaxy Cluster Suburbs": "Suburbios de Cúmulos Galácticos",
  "General of Crude": "General del Crudo",
  "Get Liberty Bucks": "Conseguir Libertólares",
  "Giant Balloon": "Globo Gigante",
  "Giant balloon eagle spotted over three states": "Avistan un águila-globo gigante sobre tres estados",
  "Give a Stump Speech for ×2 profit. Speeches stack up to 24 hours.": "Da un Mitin para ganancias ×2. Los mítines se acumulan hasta 24 horas.",
  "Give another speech to keep profits doubled.": "Da otro mitin para mantener las ganancias duplicadas.",
  "Give {n} stump speeches.": "Da {n} mítines.",
  "Global": "Globales",
  "God bless America — and every planet near it!": "¡Dios bendiga a América… y a todos los planetas cercanos!",
  "Got it!": "¡Entendido!",
  "Grassroots Campaign {r}": "Campaña de Base {r}",
  "Great Red Spot Attendant": "Encargado de la Gran Mancha Roja",
  "Great Society Plus": "Gran Sociedad Plus",
  "Greetings, Earth President. My people offer a trade agreement. Choose one — the other delegation will be… disappointed.": "Saludos, Presidente terrícola. Mi pueblo ofrece un acuerdo comercial. Elige uno; la otra delegación quedará… decepcionada.",
  "Hands-On President {n}": "Presidente Práctico {n}",
  "Haptics": "Vibración háptica",
  "Head Rancher of Mars": "Ranchero Mayor de Marte",
  "Head of Glamour": "Jefe de Glamur",
  "Heat death? You're covered.": "¿Muerte térmica? Estás cubierto.",
  "Hire": "Contratar",
  "Hire George Washingtun. He'll run the Flag Stand forever — even while you're away.": "Contrata a George Washingtun. Dirigirá el Puesto de Banderas para siempre, incluso cuando no estés.",
  "Hire every manager on {world}.": "Contrata a todos los gerentes en {world}.",
  "Hire the manager for {biz}": "Contrata al gerente de {biz}",
  "Hired": "Contratado",
  "Hold a Galactic Election": "Celebrar Elecciones Galácticas",
  "Hold a Space Election": "Celebrar Elecciones Espaciales",
  "Hold a Universal Election": "Celebrar Elecciones Universales",
  "Hold an Election": "Celebrar Elecciones",
  "Hold {n} Constitutional Conventions.": "Celebra {n} Convenciones Constitucionales.",
  "Hold {n} elections": "Celebra {n} elecciones",
  "Hold {n} elections on {world}.": "Celebra {n} elecciones en {world}.",
  "Holding an Election resets this world's cash, businesses, managers and upgrades — but your campaign attracts <b>{p}</b>. Each one boosts profit by <b>{e}%</b>. You earn more the more you've made all-time ({life}).": "Celebrar elecciones reinicia el dinero, los negocios, los gerentes y las mejoras de este mundo, pero tu campaña atrae <b>{p}</b>. Cada uno aumenta las ganancias un <b>{e}%</b>. Consigues más cuanto más hayas ganado en total ({life}).",
  "Holding an Election resets your businesses but earns Donors. Each Donor boosts profit by 2%!": "Celebrar elecciones reinicia tus negocios pero te da Donantes. ¡Cada Donante aumenta las ganancias un 2%!",
  "Hollywood Studio": "Estudio de Hollywood",
  "Home, home on the red range.": "Hogar, dulce hogar en la pradera roja.",
  "Hot Dog Commissioner": "Comisionado de Perritos Calientes",
  "How to earn": "Cómo ganar",
  "Hydrogen, regular or premium.": "Hidrógeno, normal o premium.",
  "Hyper-American": "Hiperamericano",
  "Hyper-Budget": "Hiperpresupuesto",
  "I cannot tell a lie: profits are up!": "No puedo mentir: ¡las ganancias suben!",
  "I promise lower taxes AND more fireworks!": "¡Prometo menos impuestos Y más fuegos artificiales!",
  "Import": "Importar",
  "Import failed": "Error al importar",
  "Import save": "Importar partida",
  "Infrastructure Bill": "Ley de Infraestructuras",
  "Instantly collect 1 hour of managed earnings on the current world.": "Cobra al instante 1 hora de ganancias gestionadas en el mundo actual.",
  "Instantly collect 24 hours of managed earnings on the current world.": "Cobra al instante 24 horas de ganancias gestionadas en el mundo actual.",
  "Instantly collect 7 days of managed earnings on the current world.": "Cobra al instante 7 días de ganancias gestionadas en el mundo actual.",
  "It's the weekend — the <b>🎉 event</b> is live! Visit it from the <b>🪐 Star Map</b> to earn permanent Liberty Badges.": "¡Es fin de semana y el <b>🎉 evento</b> está activo! Visítalo desde el <b>🪐 Mapa Estelar</b> para ganar Insignias de la Libertad permanentes.",
  "Join": "Unirse",
  "Jupiter Gas Station": "Gasolinera de Júpiter",
  "Jupiter gas prices soar to $4.99 per cubic kilometer": "El gas de Júpiter se dispara a $4.99 por kilómetro cúbico",
  "Keep playing": "Seguir jugando",
  "Keep tapping and buying. Save $60 to open the Bald Eagle Hatchery.": "Sigue tocando y comprando. Ahorra $60 para abrir el Criadero de Águilas Calvas.",
  "Keep your streak alive, President!": "¡Mantén viva tu racha, Presidente!",
  "Kite & Grill Master": "Maestro de Cometas y Parrillas",
  "Known Universe": "Universo Conocido",
  "LIFTOFF!": "¡DESPEGUE!",
  "Landslide Victory {r}": "Victoria Aplastante {r}",
  "Landslide victory!": "¡Victoria aplastante!",
  "Language": "Idioma",
  "Last tip: give a Stump Speech to double all profits for 4 hours. Go get 'em, President!": "Último consejo: da un Mitin para duplicar todas las ganancias durante 4 horas. ¡A por ellos, Presidente!",
  "Launch": "Lanzar",
  "Launchpad Program": "Programa de Lanzamiento",
  "Launchpad intern asks \"what if we just… went?\"": "Un becario de la plataforma pregunta: \"¿y si simplemente… fuéramos?\"",
  "Leaving {world}": "Dejando {world}",
  "Legislation for profit": "Legislación con ánimo de lucro",
  "Let's go!": "¡Vamos!",
  "Liberty Badge": "Insignia de la Libertad",
  "Liberty Badges": "Insignias de la Libertad",
  "Liberty Bucks": "Libertólares",
  "Liberty Bucks!": "¡Libertólares!",
  "Liberty Surplus": "Superávit de Libertad",
  "Liberty-Class": "Clase Libertad",
  "Live now! Ends in {t}.": "¡En vivo! Termina en {t}.",
  "Load save": "Cargar partida",
  "Lobbyist for {biz}": "Cabildero de {biz}",
  "Local eagle files for small business loan": "Águila local solicita un préstamo para pymes",
  "Location, location, light-years.": "Ubicación, ubicación, años luz.",
  "Log in every day to climb the 7-day reward ladder. Miss a day and the streak starts over.": "Entra cada día para subir la escalera de recompensas de 7 días. Si faltas un día, la racha vuelve a empezar.",
  "Login streak": "Racha de inicio de sesión",
  "Loops charge over time (even offline). Spend one to replay 30 minutes of this world's full production instantly.": "Los bucles se cargan con el tiempo (incluso sin conexión). Gasta uno para repetir al instante 30 minutos de toda la producción de este mundo.",
  "Low pass, high profits.": "Pasada baja, ganancias altas.",
  "Loyal Voter {n}": "Votante Leal {n}",
  "Lunar Cheese Mine": "Mina de Queso Lunar",
  "MAX": "MÁX",
  "Majestic. Loud. Profitable.": "Majestuosas. Ruidosas. Rentables.",
  "Majority Leader(s)": "Líder(es) de la Mayoría",
  "Make America Orbital": "Hagamos América Orbital",
  "Managers run businesses for you — even while you sleep.": "Los gerentes dirigen tus negocios, incluso mientras duermes.",
  "Manifest": "Manifiesto",
  "Manifest Destiny 2.0": "Destino Manifiesto 2.0",
  "Manifest Everything Act": "Ley del Todo Manifiesto",
  "Marching Band": "Banda de Música",
  "Marching band refuses to stop, now in its 30th hour": "La banda de música se niega a parar; ya lleva 30 horas",
  "Mars Terraform Ranch": "Rancho de Terraformación Marciano",
  "Marshall Plan (Space)": "Plan Marshall (Espacial)",
  "Martian cattle refuse to moo in low gravity": "El ganado marciano se niega a mugir en baja gravedad",
  "Max 24h · {t}": "Máx. 24 h · {t}",
  "Maxed!": "¡Al máximo!",
  "Mega Firework": "Megacohete",
  "Mega Rally": "Megamitin",
  "Mega Rally!": "¡Megamitin!",
  "Megamall Magnate": "Magnate del Megacentro",
  "Mercury Solar Ring": "Anillo Solar de Mercurio",
  "Milestones": "Hitos",
  "Milky Way": "Vía Láctea",
  "Minister of Boom": "Ministro del Estruendo",
  "Mission Accomplished {n}": "Misión Cumplida {n}",
  "Mission control reports: at <b>$1 quadrillion</b> we can fund the Moonshot. Check the <b>🪐 Star Map</b>!": "Control de misión informa: con <b>$1 mil billones</b> podemos financiar el viaje a la Luna. ¡Revisa el <b>🪐 Mapa Estelar</b>!",
  "Missions": "Misiones",
  "Missions are available on the main worlds. The weekend event has its own reward tiers — check the Rewards tab!": "Las misiones están en los mundos principales. El evento de fin de semana tiene sus propios niveles de recompensa: ¡mira la pestaña Recompensas!",
  "Missions completed": "Misiones completadas",
  "Missions — {world}": "Misiones — {world}",
  "Monster Truck Rally": "Rally de Monster Trucks",
  "Monster truck elected to county school board": "Un monster truck, elegido para el consejo escolar del condado",
  "Moon Bounce House": "Castillo Hinchable Lunar",
  "Moon Dollars": "Dólares Lunares",
  "Moon Landing Jubilee": "Jubileo del Alunizaje",
  "Moon declared the 51st state; cartographers furious": "Declaran la Luna el estado 51; los cartógrafos, furiosos",
  "More": "Más",
  "Multiversal Banker": "Banquero Multiversal",
  "Multiverse Bank": "Banco del Multiverso",
  "Multiverse bank reports you are rich in 42% of realities": "El banco del multiverso informa que eres rico en el 42% de las realidades",
  "Music": "Música",
  "My fellow Americans! Our destiny lies among the stars — but first, we need cash. Tap the Flag Stand to start earning!": "¡Compatriotas! Nuestro destino está entre las estrellas… pero primero necesitamos dinero. ¡Toca el Puesto de Banderas para empezar a ganar!",
  "My fellow Americans…": "Compatriotas…",
  "NEXT": "SIG.",
  "National Holiday": "Fiesta Nacional",
  "Nebula Paint Co.": "Pinturas Nebulosa S.A.",
  "Nebula paint recall: \"Cosmic Beige\" found to be actual beige": "Retiran la pintura nebulosa: el \"beige cósmico\" resultó ser beige normal",
  "Negotiate": "Negociar",
  "New Deal 2.0": "New Deal 2.0",
  "New business!": "¡Nuevo negocio!",
  "New frame!": "¡Nuevo marco!",
  "Next: {at} → {what}": "Siguiente: {at} → {what}",
  "Nightly at 8. Bring earplugs.": "Cada noche a las 8. Trae tapones.",
  "No ad available": "No hay anuncios disponibles",
  "Not yet": "Todavía no",
  "Nothing here yet.": "Aún no hay nada aquí.",
  "Nothing to restore": "Nada que restaurar",
  "Notifications": "Notificaciones",
  "Notifications are off": "Las notificaciones están desactivadas",
  "Now 40% more bunting.": "Ahora con un 40% más de banderines.",
  "Now in 16 million cosmic hues.": "Ahora en 16 millones de tonos cósmicos.",
  "Now running {biz} automatically.": "Ahora dirige {biz} automáticamente.",
  "Offline earnings doubled.": "Ganancias sin conexión duplicadas.",
  "Omni-Patriotic": "Omnipatriótico",
  "Omnibucks": "Omnidólares",
  "One giant leap for profits": "Un gran salto para las ganancias",
  "One small hop for a kid.": "Un pequeño salto para un niño.",
  "Orbital Megamall": "Megacentro Orbital",
  "Own <b>{n}</b> of everything → all profit ×{m} (lowest: {lo})": "Ten <b>{n}</b> de todo → ganancias ×{m} (mínimo actual: {lo})",
  "Own {n} of every business": "Ten {n} de cada negocio",
  "Own {n} of every business on {world}.": "Ten {n} de cada negocio en {world}.",
  "Own {n} {biz}": "Ten {n} {biz}",
  "Own {n} {biz}.": "Ten {n} {biz}.",
  "Owned": "Comprado",
  "Paint Commissioner": "Comisionado de Pintura",
  "Parade Float": "Carroza del Desfile",
  "Parade float achieves low orbit": "Una carroza del desfile alcanza la órbita baja",
  "Parody politicians, real productivity": "Políticos de parodia, productividad real",
  "Pass bills to multiply your profits. Upgrades stay until your next Election.": "Aprueba leyes para multiplicar tus ganancias. Las mejoras duran hasta tus próximas elecciones.",
  "Pass the zero-g gravy": "Pásame la salsa de gravedad cero",
  "Pass {n} upgrades": "Aprueba {n} mejoras",
  "Passed": "Aprobada",
  "Paste an exported save code": "Pega un código de partida exportado",
  "Patriot Donors": "Donantes Patriotas",
  "Patriotic": "Patriótico",
  "Permanent multiplier": "Multiplicador permanente",
  "Petition signed!": "¡Petición firmada!",
  "Pit Boss": "Jefe de Mesa",
  "Pluto reinstated as planet in exchange for tax incentives": "Plutón vuelve a ser planeta a cambio de incentivos fiscales",
  "Pocket of Liberty": "Bolsillo de Libertad",
  "Poll: 97% of Americans want a flag on the Moon. The other 3% want two": "Encuesta: el 97% quiere una bandera en la Luna. El otro 3% quiere dos",
  "Privacy policy": "Política de privacidad",
  "Profit bonus": "Bonus de ganancias",
  "Profit of <b>everything</b> ×{n}": "Ganancias de <b>todo</b> ×{n}",
  "Profits multiplied.": "Ganancias multiplicadas.",
  "Promote": "Ascender",
  "Pulsar Radio": "Radio Púlsar",
  "Purchase failed": "La compra falló",
  "Purchase pending": "Compra pendiente",
  "Purchased ({n})": "Compradas ({n})",
  "All worlds, Liberty Bucks and achievements on this device will be erased. Purchases can be restored.": "Se borrarán todos los mundos, Libertólares y logros de este dispositivo. Las compras se pueden restaurar.",
  "Purchases are only available in the Google Play version.": "Las compras solo están disponibles en la versión de Google Play.",
  "Purchases are processed by Google Play. Liberty Bucks are a virtual currency with no cash value.": "Google Play procesa las compras. Los Libertólares son una moneda virtual sin valor monetario.",
  "Your empire autosaves on this device and is included in your Android backup. Export a backup code to move it manually.": "Tu imperio se guarda automáticamente en este dispositivo y se incluye en tu copia de seguridad de Android. Exporta un código de respaldo para moverlo manualmente.",
  "Purchases are only available in the App Store version.": "Las compras solo están disponibles en la versión de la App Store.",
  "Purchases are processed by Apple. Liberty Bucks are a virtual currency with no cash value.": "Apple procesa las compras. Los Libertólares son una moneda virtual sin valor monetario.",
  "Purchases restored": "Compras restauradas",
  "Pyrotechnics Chief": "Jefa de Pirotecnia",
  "Quasar Operator": "Operador del Cuásar",
  "Quasar Power Plant": "Central de Cuásares",
  "Rallying the base… +4 hours of ×2 profit (max 24h)": "Movilizando a las bases… +4 horas de ganancias ×2 (máx. 24 h)",
  "Ratify": "Ratificar",
  "Reach a {n}-day login streak.": "Consigue una racha de {n} días.",
  "Ready to <b>{verb}</b>? We'll lose our cash, businesses, managers and upgrades on {world} — but gain <b>+{n} {p}</b>, boosting all profit here. The campaign never stops!": "¿Listo para <b>{verb}</b>? Perderemos el dinero, los negocios, los gerentes y las mejoras de {world}, pero ganaremos <b>+{n} {p}</b>, que aumentan todas las ganancias aquí. ¡La campaña nunca se detiene!",
  "Record crowds at Freedom Fest; hot dog supply critical": "Multitudes récord en el Festival de la Libertad; suministro de perritos crítico",
  "Reduce motion": "Reducir movimiento",
  "Relish floats. Buns do too.": "El pepinillo flota. El pan, también.",
  "Reminders (offline cap, speeches, daily)": "Recordatorios (límite sin conexión, mítines, diario)",
  "Replay 30 min": "Repetir 30 min",
  "Replay history for profit in the Known Universe.": "Repite la historia para ganar en el Universo Conocido.",
  "Replay tutorial": "Repetir tutorial",
  "Replayed 30 minutes: +{x}": "30 minutos repetidos: +{x}",
  "Reset everything": "Reiniciar todo",
  "Reset everything?": "¿Reiniciar todo?",
  "Resets <b>all four worlds</b> — cash, businesses, upgrades and prestige currency — in exchange for Amendments. Each Amendment multiplies all profit by ×{p} and adds +{a}% prestige effectiveness, forever. Worlds stay unlocked.": "Reinicia <b>los cuatro mundos</b> (dinero, negocios, mejoras y moneda de prestigio) a cambio de Enmiendas. Cada Enmienda multiplica todas las ganancias por ×{p} y añade +{a}% de efectividad de prestigio, para siempre. Los mundos siguen desbloqueados.",
  "Resort Host": "Anfitrión del Resort",
  "Restore purchases": "Restaurar compras",
  "Reward tiers grant ★ and permanent Liberty Badges.": "Los niveles de recompensa dan ★ e Insignias de la Libertad permanentes.",
  "Rewards": "Premios",
  "Rodeo Champion": "Campeón de Rodeo",
  "Root User": "Superusuario",
  "Run {biz}": "Operar {biz}",
  "Saturn Ring Resort": "Resort de los Anillos de Saturno",
  "Saturn ring resort wins \"Most Rings\" award again": "El resort de Saturno vuelve a ganar el premio \"Más Anillos\"",
  "Save code": "Código de partida",
  "Save data": "Datos de guardado",
  "Save exported": "Partida exportada",
  "Secretary of Pie": "Secretario de Tartas",
  "Secretary ✓": "Secretario ✓",
  "Sequels to sequels.": "Secuelas de secuelas.",
  "Settings": "Ajustes",
  "Seventy-six trombones, minimum.": "Setenta y seis trombones, como mínimo.",
  "Shale Rig": "Plataforma de Esquisto",
  "Shock Jock": "Locutor Polémico",
  "Showrunner": "Productor Ejecutivo",
  "Sign it": "Firmarla",
  "Simulation Admin Console": "Consola del Administrador de la Simulación",
  "Skip tutorial": "Saltar tutorial",
  "Sky Patrol {n}": "Patrulla del Cielo {n}",
  "Sky bonus!": "¡Bonus del cielo!",
  "Sky bonuses caught": "Bonus del cielo atrapados",
  "Solar Evangelist": "Evangelista Solar",
  "Solar Flares": "Llamaradas Solares",
  "Solar System": "Sistema Solar",
  "Solar flare!": "¡Llamarada solar!",
  "Sound & feel": "Sonido y tacto",
  "Sound effects": "Efectos de sonido",
  "Space Cowboy Rodeo": "Rodeo de Vaqueros Espaciales",
  "Space Force Veterans": "Veteranos de la Fuerza Espacial",
  "Space Shuttle Flyover": "Sobrevuelo del Transbordador",
  "Space cowboy lassos a moon; moon unimpressed": "Vaquero espacial enlaza una luna; la luna no se inmuta",
  "Speak softly and carry a big rocket!": "¡Habla suave y lleva un gran cohete!",
  "Speeches stack up to 24 hours.": "Los mítines se acumulan hasta 24 horas.",
  "Spend freedom, earn more freedom": "Gasta libertad, gana más libertad",
  "Sphere Architect": "Arquitecto de la Esfera",
  "Star Forge": "Forja Estelar",
  "Star Map": "Mapa Estelar",
  "Star-Spangled": "Estrellado",
  "Star-Spangled Tycoon {v} — a parody idle game. All politicians depicted are historical figures or fictional characters, drawn as cartoon caricatures with parody names. No endorsement is implied.": "Star-Spangled Tycoon {v}: un juego idle de parodia. Todos los políticos que aparecen son figuras históricas o personajes ficticios, dibujados como caricaturas con nombres paródicos. No implica ningún respaldo.",
  "Stars: forged in the USA.": "Estrellas: forjadas en EE. UU.",
  "Statistics": "Estadísticas",
  "Stimulus Check": "Cheque de Estímulo",
  "Store": "Tienda",
  "Store unavailable": "Tienda no disponible",
  "String Theorist": "Teórico de Cuerdas",
  "Stump Speaker {n}": "Orador de Mitin {n}",
  "Stump Speech": "Mitin",
  "Stump speeches": "Mítines",
  "Suburb Planner": "Urbanista de Suburbios",
  "Sunday! Sunday! SUNDAY!": "¡Domingo! ¡Domingo! ¡DOMINGO!",
  "Sunlight, now with a subscription.": "Luz solar, ahora con suscripción.",
  "Supporters are lining up! Holding an <b>🗳️ Election</b> resets this world, but each supporter boosts profit forever. The more you earn, the bigger the war chest.": "¡Los simpatizantes hacen cola! Celebrar <b>🗳️ Elecciones</b> reinicia este mundo, pero cada simpatizante aumenta las ganancias para siempre. Cuanto más ganes, mayor será el fondo de campaña.",
  "Take me to your lobbyist.": "Llévame ante tu cabildero.",
  "Talk radio at 700 pulses/sec.": "Radio hablada a 700 pulsos por segundo.",
  "Tap Negotiate to choose a treaty.": "Toca Negociar para elegir un tratado.",
  "Tap businesses {n} times.": "Toca negocios {n} veces.",
  "Tap the Flag Stand to make your first dollar!": "¡Toca el Puesto de Banderas para ganar tu primer dólar!",
  "Tap to catch the bonus!": "¡Toca para atrapar el bonus!",
  "Tax Cut for Everyone": "Rebaja de Impuestos para Todos",
  "Tear down this… asteroid!": "¡Derribe este… asteroide!",
  "Temporal Loop!": "¡Bucle Temporal!",
  "Temporal Loops": "Bucles Temporales",
  "Temporal Loops fully charged": "Bucles Temporales cargados al máximo",
  "Text size": "Tamaño del texto",
  "Thank you, Patriot!": "¡Gracias, Patriota!",
  "Thanks for celebrating! Your badges are yours to keep.": "¡Gracias por celebrar! Las insignias son tuyas.",
  "Thanksgiving Space Parade": "Desfile Espacial de Acción de Gracias",
  "That code doesn't look like a save.": "Ese código no parece una partida guardada.",
  "The Cabinet — {world}": "El Gabinete — {world}",
  "The Grand Omnibus": "La Gran Ley Ómnibus",
  "The Sun erupts every few minutes, supercharging one business to ×5 speed for 45 seconds. Tap the flare to extend it!": "El Sol erupciona cada pocos minutos y acelera un negocio a velocidad ×5 durante 45 segundos. ¡Toca la llamarada para extenderla!",
  "The Sun is simmering…": "El Sol está a fuego lento…",
  "The United States of Everything": "Los Estados Unidos de Todo",
  "The buck stops… at the space station!": "La responsabilidad acaba… ¡en la estación espacial!",
  "The crowd goes wild!": "¡El público enloquece!",
  "The crowd needs a rest": "El público necesita un descanso",
  "The final frontier! Every galaxy, every dimension, every timeline. Temporal Loops charge up over time — spend them to replay history for profit.": "¡La última frontera! Cada galaxia, cada dimensión, cada línea temporal. Los Bucles Temporales se cargan con el tiempo: gástalos para repetir la historia y ganar.",
  "The grateful citizens chipped in {x}.": "Los ciudadanos agradecidos aportaron {x}.",
  "The house always wins. Forever.": "La casa siempre gana. Para siempre.",
  "The only thing we have to fear is running out of eagles!": "¡Lo único que debemos temer es quedarnos sin águilas!",
  "The weekend event has ended": "El evento de fin de semana terminó",
  "This cannot be undone": "No se puede deshacer",
  "Three stories of inflatable eagle.": "Tres pisos de águila hinchable.",
  "Tier {a}/{b}": "Nivel {a}/{b}",
  "Tier {n}": "Nivel {n}",
  "Time Tour Guide": "Guía de Viajes en el Tiempo",
  "Time Travel Tourism": "Turismo de Viajes en el Tiempo",
  "Time Warp: 1 Day": "Salto Temporal: 1 día",
  "Time Warp: 1 Hour": "Salto Temporal: 1 hora",
  "Time Warp: 1 Week": "Salto Temporal: 1 semana",
  "Time played": "Tiempo jugado",
  "Time to delegate. Open the Cabinet to hire a manager.": "Hora de delegar. Abre el Gabinete para contratar a un gerente.",
  "Time tourists spoil the ending of history": "Turistas del tiempo destripan el final de la historia",
  "Time warp!": "¡Salto temporal!",
  "Toll Collector": "Cobrador de Peajes",
  "Too close to call — until it isn't": "Demasiado reñido… hasta que deja de serlo",
  "Town Hall": "Ayuntamiento",
  "Transcendent": "Trascendente",
  "Travel": "Viajar",
  "Treasurer of Brrr": "Tesorero del Brrr",
  "Treaty signed!": "¡Tratado firmado!",
  "Truck Rally Announcer": "Locutor del Rally",
  "Try again in a moment.": "Inténtalo de nuevo en un momento.",
  "Unanimous every time.": "Unánime siempre.",
  "Universal Constitution": "Constitución Universal",
  "Universe expands; property taxes expand faster": "El universo se expande; los impuestos inmobiliarios, más rápido",
  "Unlock": "Desbloquear",
  "Unlock {biz} for {cost}": "Desbloquear {biz} por {cost}",
  "Unlock {world}.": "Desbloquea {world}.",
  "Unlocks": "Desbloqueos",
  "Unlocks after you reach the Known Universe.": "Se desbloquea al llegar al Universo Conocido.",
  "Upgrades": "Mejoras",
  "Upgrades — {world}": "Mejoras — {world}",
  "Vault of Liberty": "Bóveda de Libertad",
  "Venus weather forecast: 900°F and freedom": "Pronóstico en Venus: 480 °C y libertad",
  "Veterans": "Veteranos",
  "Visible from Mars. Literally.": "Visible desde Marte. Literalmente.",
  "Visit 1776. Again.": "Visita 1776. Otra vez.",
  "Volume": "Volumen",
  "Vote!": "¡A votar!",
  "Walk the dog across spacetime.": "Pasea al perro por el espacio-tiempo.",
  "Warp Drive Dealership": "Concesionario de Motores Warp",
  "Warp Salesman": "Vendedor de Warp",
  "Warp gate online! 100 billion stars, and not one American franchise. Alien envoys will offer treaties — choose wisely!": "¡Puerta warp en línea! Cien mil millones de estrellas y ni una sola franquicia americana. Los enviados alienígenas ofrecerán tratados: ¡elige con sabiduría!",
  "Watch": "Ver",
  "Watch a short ad for ★{lb} — {n} left today": "Mira un anuncio corto por ★{lb}: quedan {n} hoy",
  "Watch ad: ×2": "Ver anuncio: ×2",
  "Waving since 1776.": "Ondeando desde 1776.",
  "We can't see it, but we sell it.": "No la vemos, pero la vendemos.",
  "We choose to go to the Moon — and also the gift shop!": "¡Elegimos ir a la Luna… y también a la tienda de regalos!",
  "We made it off-world! The Moon, Mars, and the gas giants await — every rock a new strip mall. Watch for solar flares: they supercharge a business!": "¡Salimos del planeta! La Luna, Marte y los gigantes gaseosos nos esperan: cada roca, un nuevo centro comercial. Atento a las llamaradas solares: ¡aceleran un negocio!",
  "We put a fence around the Sun.": "Le pusimos una valla al Sol.",
  "We the Everyone…": "Nosotros, el Todo…",
  "We were right all along.": "Teníamos razón desde el principio.",
  "We'll deliver it as soon as it's approved.": "Lo entregaremos en cuanto se apruebe.",
  "Weekend Event": "Evento de fin de semana",
  "Welcome back, President! You were away for <b>{d}</b>{cap}. Your Cabinet kept the economy humming:": "¡Bienvenido de nuevo, Presidente! Estuviste fuera <b>{d}</b>{cap}. Tu Gabinete mantuvo la economía en marcha:",
  "Welcome to {world}": "Bienvenido a {world}",
  "While you were away…": "Mientras no estabas…",
  "Working…": "Procesando…",
  "Wormhole Toll Road": "Autopista de Peaje de Agujeros de Gusano",
  "Wormhole toll road adds carpool lane for binary stars": "La autopista de agujeros de gusano añade carril para estrellas binarias",
  "Yee-haw in zero gravity.": "Yiijaa en gravedad cero.",
  "You are here": "Estás aquí",
  "You completed a mission! Open <b>🎯 Missions</b> to claim your ★ Liberty Bucks.": "¡Completaste una misión! Abre <b>🎯 Misiones</b> para reclamar tus ★ Libertólares.",
  "Your Stump Speech wore off": "Tu Mitin se acabó",
  "Your daily reward is ready": "Tu recompensa diaria está lista",
  "Your device clock moved backwards, so offline earnings were skipped.": "El reloj de tu dispositivo retrocedió, así que se omitieron las ganancias sin conexión.",
  "Your empire autosaves on this device and syncs to iCloud. Export a backup code to move it manually.": "Tu imperio se guarda automáticamente en este dispositivo y se sincroniza con iCloud. Exporta un código de respaldo para moverlo manualmente.",
  "Your money, in every reality.": "Tu dinero, en todas las realidades.",
  "Your sponsor's message…": "Un mensaje de nuestro patrocinador…",
  "Zero percent APR, 9.9 warp.": "0% TAE, warp 9.9.",
  "Zero-G Hot Dog Cart": "Carrito de Perritos Gravedad Cero",
  "basic": "básico",
  "billion": "mil millones",
  "bronze": "bronce",
  "businesses 1–5": "negocios 1–5",
  "businesses 6–10": "negocios 6–10",
  "buy the business first": "compra primero el negocio",
  "current ×{n}": "actual ×{n}",
  "current: speed ×{s}, profit ×{p}": "actual: velocidad ×{s}, ganancias ×{p}",
  "decillion": "mil quintillones",
  "diamond": "diamante",
  "ends in {t}": "termina en {t}",
  "even-numbered businesses": "negocios pares",
  "everything": "todo",
  "for 10 minutes": "durante 10 minutos",
  "gold": "oro",
  "million": "millones",
  "next at {x}": "siguiente en {x}",
  "next in {t}": "siguiente en {t}",
  "nonillion": "quintillones",
  "octillion": "mil cuatrillones",
  "odd-numbered businesses": "negocios impares",
  "per second": "por segundo",
  "platinum": "platino",
  "profit ×{n}": "ganancias ×{n}",
  "quadrillion": "mil billones",
  "quintillion": "trillones",
  "runs": "dirige",
  "septillion": "cuatrillones",
  "sextillion": "mil trillones",
  "silver": "plata",
  "speed ×{n}": "velocidad ×{n}",
  "spend {p} (they stop boosting profit)": "gasta {p} (dejan de aumentar las ganancias)",
  "sudo make america great.": "sudo make america great.",
  "tap ☀ to extend": "toca ☀ para extender",
  "trillion": "billones",
  "{adj} {name}": "{name} {adj}",
  "{a} / {b} achievements": "{a} / {b} logros",
  "{a} / {b} complete": "{a} / {b} completadas",
  "{biz} at ×5 speed · {t}": "{biz} a velocidad ×5 · {t}",
  "{biz} earned a {tier} frame.": "{biz} ganó un marco de {tier}.",
  "{biz} is now 90% cheaper.": "{biz} ahora es un 90% más barato.",
  "{biz} is open. Tap its icon to earn.": "{biz} ya está abierto. Toca su icono para ganar.",
  "{biz} is running at ×5 speed. Tap ☀ to extend!": "{biz} funciona a velocidad ×5. ¡Toca ☀ para extenderlo!",
  "{biz} milestone!": "¡Hito de {biz}!",
  "{biz} ×{n}": "{biz} ×{n}",
  "{biz} — {n} owned": "{biz}: tienes {n}",
  "{name} hired!": "¡{name} contratado!",
  "{name} takes the podium": "{name} sube al estrado",
  "{n} Liberty Bucks": "{n} Libertólares",
  "{n} Terms ({world})": "{n} Mandatos ({world})",
  "{n} bills passed!": "¡{n} leyes aprobadas!",
  "{n} elections held on {world}": "{n} elecciones celebradas en {world}",
  "{n} item(s) restored.": "{n} artículo(s) restaurado(s).",
  "{what} at {n} owned": "{what} al tener {n}",
  "{world} Tycoon {r}": "Magnate de {world} {r}",
  "{world} all-time earnings": "Ganancias totales en {world}",
  "{world} now earns ×{n} forever.": "{world} ahora gana ×{n} para siempre.",
  "×10 for 15m": "×10 durante 15 min",
  "×10 profit for 15 minutes.": "Ganancias ×10 durante 15 minutos.",
  "×2 active · {t}": "×2 activo · {t}",
  "×2 for 4h": "×2 durante 4 h",
  "×2 profit for 4 hours": "Ganancias ×2 durante 4 horas",
  "×2 profit · {t} remaining": "Ganancias ×2 · quedan {t}",
  "≈ {x} now": "≈ {x} ahora",
  "▶ Watch ad: ×2 for 4h": "▶ Ver anuncio: ×2 durante 4 h",
  "Progress not saved": "Progreso no guardado",
  "Your browser storage is full or blocked. Export a backup code in Settings to keep your empire safe.": "El almacenamiento de tu navegador está lleno o bloqueado. Exporta un código de respaldo en Ajustes para proteger tu imperio.",
  "That save is from a newer version of the game. Update first, then import it.": "Esa partida es de una versión más nueva del juego. Actualiza primero y luego impórtala.",
  "Save recovered": "Partida recuperada",
  "Your save couldn't be read, so we restored your most recent backup ({time}). A little recent progress may be missing.": "No se pudo leer tu partida, así que restauramos tu copia de seguridad más reciente ({time}). Puede faltar algo de progreso reciente.",
  "Save couldn't be read": "No se pudo leer la partida",
  "Your save was damaged and no backup could be loaded, so a new game was started. The damaged save has been kept on this device — contact support and we'll try to recover it.": "Tu partida estaba dañada y no se pudo cargar ninguna copia de seguridad, así que se empezó una nueva. La partida dañada se ha conservado en este dispositivo: contacta con soporte e intentaremos recuperarla.",
  "All worlds, Liberty Bucks and achievements saved in this browser will be erased.": "Se borrarán todos los mundos, Libertólares y logros guardados en este navegador.",
  "Your empire autosaves to your CrazyGames account. Export a backup code to keep a copy.": "Tu imperio se guarda automáticamente en tu cuenta de CrazyGames. Exporta un código de respaldo para conservar una copia.",
  "Your empire autosaves in this browser. Clearing site data erases it, so export a backup code to keep a copy.": "Tu imperio se guarda automáticamente en este navegador. Borrar los datos del sitio lo elimina, así que exporta un código de respaldo para conservar una copia."
});
