/* Spanish strings for the live-ops systems (Liberty Pass, offers, Space Race,
 * Executive Orders, Presidential Library, Style). Merged into the main 'es' pack. */
I18N.register('es', {
  "Helps us find what to improve. No personal data, no advertising ID — just anonymous gameplay events.": "Nos ayuda a saber qué mejorar. Sin datos personales ni identificador de publicidad: solo eventos de juego anónimos.",
  "No ad right now": "No hay anuncios ahora",
  "Not now": "Ahora no",
  "Privacy": "Privacidad",
  "Remind me": "Recuérdamelo",
  "Reminders": "Recordatorios",
  "Share anonymous usage stats": "Compartir estadísticas de uso anónimas",
  "This item isn't available from Google Play right now. Please try again later.": "Este artículo no está disponible en Google Play en este momento. Inténtalo más tarde.",
  "This item isn't available from the App Store right now. Please try again later.": "Este artículo no está disponible en la App Store en este momento. Inténtalo más tarde.",
  "This one's on us, President!": "¡Esta corre por nuestra cuenta, Presidente!",
  "Welcome back! Want a heads-up when your treasury is overflowing, your daily reward is ready or the Space Race is about to end? You can change this anytime in Settings.": "¡Bienvenido de nuevo! ¿Quieres un aviso cuando tu tesoro se desborde, tu recompensa diaria esté lista o la Carrera Espacial esté por terminar? Puedes cambiarlo cuando quieras en Ajustes.",
  "+ exclusive {kind}: {name}": "+ {kind} exclusivo: {name}",
  "+50% ★ from missions": "+50 % de ★ en las misiones",
  "3 of a plank: ×{a} · all 5: ×{b} · one of each: ×{c}": "3 de una línea: ×{a} · las 5: ×{b} · una de cada: ×{c}",
  "<b>{biz}</b> profit ×10, but <b>{biz2}</b> profit ×½": "Ganancias de <b>{biz}</b> ×10, pero de <b>{biz2}</b> ×½",
  "<b>{biz}</b> profit ×4 (business #{n} on every world)": "Ganancias de <b>{biz}</b> ×4 (negocio n.º {n} en todos los mundos)",
  "A new Liberty Pass season!": "¡Nueva temporada del Pase de la Libertad!",
  "A new rival every Monday": "Un rival nuevo cada lunes",
  "A penny saved is a Liberty Pass tier earned! Everything you do now earns <b>Pass XP</b>. Climb 30 tiers each season for Liberty Bucks, boosts and Library cards.": "¡Centavo ahorrado, nivel del Pase ganado! Todo lo que haces ahora da <b>XP del Pase</b>. Sube 30 niveles cada temporada para ganar Libertólares, impulsos y cartas de la Biblioteca.",
  "After tier {n}, every {x} XP earns ★{lb}.": "Después del nivel {n}, cada {x} XP da ★{lb}.",
  "Ahead by {n}": "Ventaja de {n}",
  "All profit ×1.5": "Todas las ganancias ×1,5",
  "All slots are full — choose an order to replace.": "Todos los espacios están llenos: elige una orden para reemplazar.",
  "All your moons are belong to us.": "Todas tus lunas son nuestras.",
  "Alpha Centauri": "Alfa Centauri",
  "American Landmarks": "Monumentos de EE. UU.",
  "Apollo Silver": "Plata Apolo",
  "Apollo White": "Blanco Apolo",
  "Asteroid Belt": "Cinturón de asteroides",
  "Aviator Shades": "Gafas de aviador",
  "Behind by {n}": "Atrás por {n}",
  "Beige is a color. We checked.": "El beige es un color. Lo comprobamos.",
  "Bronze League": "Liga de Bronce",
  "Business milestone": "Hito de negocio",
  "Businesses 1–5: profit ×2": "Negocios 1–5: ganancias ×2",
  "Businesses 6–10: profit ×2": "Negocios 6–10: ganancias ×2",
  "Buy American Act": "Ley Compre Americano",
  "Cabinet Looks": "Estilos del Gabinete",
  "Campaign Finance Act": "Ley de Financiación de Campañas",
  "Campaign donation!": "¡Donación de campaña!",
  "Claim all ({n})": "Reclamar todo ({n})",
  "Claim {w}": "Reclamar {w}",
  "Claim ×2": "Reclamar ×2",
  "Classic Glory": "Gloria Clásica",
  "Collect the Cabinet, complete the sets": "Colecciona el Gabinete, completa las series",
  "Collect {n} Presidential Library cards.": "Colecciona {n} cartas de la Biblioteca Presidencial.",
  "Collected": "Coleccionadas",
  "Colonial Charter": "Carta Colonial",
  "Colonial Tribute doubled (×10)": "Tributo Colonial duplicado (×10)",
  "Common": "Común",
  "Compared with the ★100 pack. One purchase per player; this offer won't come back.": "Comparado con el paquete de ★100. Una compra por jugador; esta oferta no volverá.",
  "Complete: Freedom Fest profit ×{m}": "Completa: ganancias del Festival de la Libertad ×{m}",
  "Daily reward": "Recompensa diaria",
  "Declaration Parchment": "Pergamino de la Declaración",
  "Donation": "Donación",
  "Each: +{p}% profit on every main world · complete: ×{m}": "Cada una: +{p} % de ganancias en todos los mundos principales · completa: ×{m}",
  "Each: +{p}% {world} profit · complete: ×{m}": "Cada una: +{p} % de ganancias en {world} · completa: ×{m}",
  "Earn XP from missions, daily rewards, speeches, sky bonuses, orders and more.": "Gana XP con misiones, recompensas diarias, discursos, bonos del cielo, órdenes y más.",
  "Earn race points": "Gana puntos de carrera",
  "Earth Cabinet": "Gabinete de la Tierra",
  "Economy": "Economía",
  "Election": "Elección",
  "Empty slot": "Espacio vacío",
  "Equip": "Equipar",
  "Equipped": "Equipado",
  "Every 5th mission, day 7 of the login ladder, Space Race results, event badges and the free Liberty Pass track. Cards are never sold.": "Cada 5.ª misión, el día 7 de la escalera diaria, los resultados de la Carrera Espacial, las insignias de eventos y la vía gratuita del Pase de la Libertad. Las cartas nunca se venden.",
  "Every business is 15% cheaper": "Todos los negocios cuestan un 15 % menos",
  "Every business runs 25% faster": "Todos los negocios funcionan un 25 % más rápido",
  "Executive Order": "Orden ejecutiva",
  "Executive Order signed!": "¡Orden ejecutiva firmada!",
  "Executive Orders": "Órdenes ejecutivas",
  "Founders' Seal": "Sello de los Fundadores",
  "Founders' Season": "Temporada de los Fundadores",
  "Free": "Gratis",
  "Freedom Fest Crew": "Equipo del Festival de la Libertad",
  "Galactic Bundle": "Paquete Galáctico",
  "Galactic Cabinet": "Gabinete Galáctico",
  "Galactic Frontier": "Frontera Galáctica",
  "Galactic Frontier Season": "Temporada de la Frontera Galáctica",
  "Galactic League": "Liga Galáctica",
  "Gilded Age": "Edad Dorada",
  "Gold League": "Liga de Oro",
  "Golden Gate Bridge": "Puente Golden Gate",
  "Golden Helmets": "Cascos dorados",
  "Hah! You call that a space program? Every week a rival power races you to the stars. Earn <b>race points</b> by playing — missions, speeches, milestones — and beat us by Monday for rewards and a league promotion.": "¡Ja! ¿A eso le llamas programa espacial? Cada semana una potencia rival compite contigo hacia las estrellas. Gana <b>puntos de carrera</b> jugando (misiones, discursos, hitos) y derrótanos antes del lunes para ganar recompensas y subir de liga.",
  "Hire a manager": "Contratar a un gerente",
  "Hologram": "Holograma",
  "How to earn cards": "Cómo ganar cartas",
  "Icon Frames": "Marcos de icono",
  "In effect ({a}/{b})": "En vigor ({a}/{b})",
  "It takes effect immediately.": "Entra en vigor de inmediato.",
  "Jupiter": "Júpiter",
  "Later": "Más tarde",
  "Launch a world": "Lanzar un mundo",
  "Launchpad": "Plataforma de lanzamiento",
  "Laurel Wreath": "Corona de laurel",
  "League": "Liga",
  "Leagues": "Ligas",
  "Legendary": "Legendaria",
  "Liberty": "Libertad",
  "Liberty Bell": "Campana de la Libertad",
  "Liberty Pass": "Pase de la Libertad",
  "Liberty Torch": "Antorcha de la Libertad",
  "Librarian {n}": "Bibliotecario {n}",
  "Library card": "Carta de la Biblioteca",
  "Library card: {name}": "Carta de la Biblioteca: {name}",
  "Limited time · ends in {t}": "Tiempo limitado · termina en {t}",
  "Lose: {w}": "Derrota: {w}",
  "Low Orbit": "Órbita baja",
  "Main Street Relief Act": "Ley de Alivio de la Calle Principal",
  "Mandate of the People": "Mandato del Pueblo",
  "Mars": "Marte",
  "Mission": "Misión",
  "Moonshot Bundle": "Paquete Alunizaje",
  "Moonshot Season": "Temporada Alunizaje",
  "Mount Rushmore": "Monte Rushmore",
  "Mr. President, your pen awaits! Each day you may sign one <b>Executive Order</b> from a draft of three. Keep up to five in effect — and match their planks for bonus profit.": "¡Señor Presidente, su pluma le espera! Cada día puede firmar una <b>orden ejecutiva</b> entre tres opciones. Mantenga hasta cinco en vigor y combine sus líneas para obtener ganancias extra.",
  "Nebula": "Nebulosa",
  "New draft": "Nuevas opciones",
  "New league: {l}": "Nueva liga: {l}",
  "New!": "¡Nuevo!",
  "Next tier": "Siguiente nivel",
  "No thanks": "No, gracias",
  "Only {d} left this season — premium applies to the current season only.": "Solo quedan {d} de temporada: el pase prémium solo vale para la temporada actual.",
  "Open Door Act": "Ley de Puertas Abiertas",
  "Open Skies Act": "Ley de Cielos Abiertos",
  "Open the Presidential Library to see your collection.": "Abre la Biblioteca Presidencial para ver tu colección.",
  "Orders": "Órdenes",
  "Party Hats": "Gorros de fiesta",
  "Pass rewards claimed!": "¡Recompensas del Pase reclamadas!",
  "Pass {a}/{b}": "Pase {a}/{b}",
  "Patriot Blue": "Azul Patriota",
  "Pen Is Mightier {n}": "Más poderosa que la espada {n}",
  "Petitions pay ×3 and treaties last twice as long": "Las peticiones pagan ×3 y los tratados duran el doble",
  "Plank bonus: all profit ×{m}": "Bono de líneas: todas las ganancias ×{m}",
  "Platinum League": "Liga de Platino",
  "Pluto": "Plutón",
  "Premium": "Prémium",
  "Premium Liberty Pass unlocked! Claim your rewards in the Pass.": "¡Pase de la Libertad Prémium desbloqueado! Reclama tus recompensas en el Pase.",
  "Premium Pass": "Pase Prémium",
  "Premium Pass active — thank you, Patriot!": "Pase Prémium activo. ¡Gracias, patriota!",
  "Presidential Library": "Biblioteca Presidencial",
  "Race rewards": "Recompensas de la carrera",
  "Rallying the base… +{h} hours of ×2 profit (max 24h)": "Animando a las bases… +{h} horas de ganancias ×2 (máx. 24 h)",
  "Rare": "Rara",
  "Reminders (speeches, daily, Space Race)": "Recordatorios (discursos, recompensa diaria, Carrera Espacial)",
  "Replace": "Reemplazar",
  "Resistance is inefficient.": "Resistirse es ineficiente.",
  "Saturn": "Saturno",
  "Saturn V": "Saturno V",
  "Season ends in": "La temporada termina en",
  "Season of Liberty": "Temporada de la Libertad",
  "Show me": "Muéstramelo",
  "Sign": "Firmar",
  "Sign one Executive Order per day. Up to {n} stay in effect on the four main worlds until you replace them. Matching planks earn bonuses!": "Firma una orden ejecutiva al día. Hasta {n} siguen en vigor en los cuatro mundos principales hasta que las reemplaces. ¡Combinar líneas da bonos!",
  "Sign {n} Executive Orders.": "Firma {n} órdenes ejecutivas.",
  "Signed {n} orders": "{n} órdenes firmadas",
  "Signed! A new draft arrives in {t}.": "¡Firmada! Nuevas opciones en {t}.",
  "Silver League": "Liga de Plata",
  "Sky bonus": "Bono del cielo",
  "Sky bonuses pay ×3": "Los bonos del cielo pagan ×3",
  "So close!": "¡Por poco!",
  "Solar Cabinet": "Gabinete Solar",
  "Solar Flares last twice as long, at ×8 speed": "Las erupciones solares duran el doble, a velocidad ×8",
  "Solar Subsidy": "Subsidio Solar",
  "Space": "Espacio",
  "Space Helmets": "Cascos espaciales",
  "Space Industry Act": "Ley de la Industria Espacial",
  "Space Race": "Carrera Espacial",
  "Space Race won!": "¡Carrera Espacial ganada!",
  "Space Racer {n}": "Corredor espacial {n}",
  "Star-Spangled Ring": "Anillo Estrellado",
  "Starter Pack": "Paquete de inicio",
  "Statue of Liberty": "Estatua de la Libertad",
  "Stimulus Checks": "Cheques de estímulo",
  "Stump Speech": "Discurso de campaña",
  "Stump Speeches last 6 hours": "Los discursos de campaña duran 6 horas",
  "Style": "Estilo",
  "Style is purely cosmetic — it never changes your profits. Buy with ★ Liberty Bucks, or earn exclusives from the Liberty Pass and special bundles.": "El estilo es solo estético: nunca cambia tus ganancias. Cómpralo con ★ Libertólares o gana exclusivos en el Pase de la Libertad y en paquetes especiales.",
  "Synthwave Senate": "Senado Synthwave",
  "Tax Holiday": "Vacaciones Fiscales",
  "Temporal Loops charge twice as fast": "Los bucles temporales se cargan el doble de rápido",
  "The Capitol": "El Capitolio",
  "The Grand Duchy of Blandovia": "El Gran Ducado de Sosovia",
  "The Great Seal": "El Gran Sello",
  "The Kingdom of Meh": "El Reino de Bah",
  "The Moon": "La Luna",
  "The New Deal": "El Nuevo Trato",
  "The Robo-Republic of Nulltopia": "La Robo-República de Nulotopía",
  "The Space Race ends in 3 hours!": "¡La Carrera Espacial termina en 3 horas!",
  "The Zorgon Hegemony": "La Hegemonía Zorgon",
  "The rival is ahead. Time for a comeback!": "El rival va delante. ¡Hora de remontar!",
  "The rival is ahead. Win this week for {w}.": "El rival va delante. Gana esta semana para obtener {w}.",
  "Themes": "Temas",
  "This week's rival": "Rival de esta semana",
  "Tier": "Nivel",
  "Time Dilation Act": "Ley de Dilatación Temporal",
  "Today's draft": "Opciones de hoy",
  "Tranquility Base": "Base Tranquilidad",
  "Unequip": "Quitar",
  "Unity": "Unidad",
  "Universal Cabinet": "Gabinete Universal",
  "Unlock Premium": "Desbloquear Prémium",
  "Victory!": "¡Victoria!",
  "We'll get to space eventually.": "Ya llegaremos al espacio algún día.",
  "Welcome Back Bundle": "Paquete de Bienvenida",
  "Win the weekly Space Race {n} times.": "Gana la Carrera Espacial semanal {n} veces.",
  "Win: {w}": "Victoria: {w}",
  "Winning promotes you to the next league.": "Ganar te asciende a la siguiente liga.",
  "World event (petition, flare, treaty, loop)": "Evento del mundo (petición, erupción, tratado, bucle)",
  "You": "Tú",
  "You beat {r} {a} to {b}.": "Venciste a {r} por {a} a {b}.",
  "You earned your first <b>Presidential Library</b> card! Collect the whole Cabinet of a world to multiply its profits.": "¡Ganaste tu primera carta de la <b>Biblioteca Presidencial</b>! Colecciona todo el Gabinete de un mundo para multiplicar sus ganancias.",
  "You're ahead — hold the lead!": "Vas delante: ¡mantén la ventaja!",
  "You're ahead! Keep it up to win {w} this week.": "¡Vas delante! Sigue así para ganar {w} esta semana.",
  "icon frame": "marco de icono",
  "theme": "tema",
  "unlocks a second reward on every tier: {lb} ★ in total, Time Warps, Mega Rallies and the season-exclusive {x}. Rewards for tiers you've already reached are granted instantly.": "desbloquea una segunda recompensa en cada nivel: {lb} ★ en total, saltos temporales, megamítines y el exclusivo de temporada {x}. Las recompensas de los niveles que ya alcanzaste se entregan al instante.",
  "you are here": "estás aquí",
  "{d} warp": "salto de {d}",
  "{n} Library cards": "{n} cartas de la Biblioteca",
  "{n} Library cards!": "¡{n} cartas de la Biblioteca!",
  "{r} won {b} to {a}.": "{r} ganó por {b} a {a}.",
  "{x}× the Liberty Bucks per dollar": "{x}× Libertólares por dólar",
  "×2 for {h}h": "×2 durante {h} h"
});
